### ISSUE TITLE
Can't run npm run markdown

### ISSUE THREAD

**Issue by hpez** [bnb/good-first-issue#102]
After running `npm run markdown` I get the following result:
![screenshot from 2019-01-15 21-52-14](https://user-images.githubusercontent.com/23010096/51200868-df1e0080-190f-11e9-890a-5428d43d7e1a.png)

**Comment by hemal7735** [comment]
@hpez thank you for creating the issue. Can you elaborate more on the steps that you followed from the beginning (starting from git clone)?

**Comment by hpez** [comment]
git clone ...
cd good-first-issue/data/
vim projects.json and added an entry
and npm run markdown

**Comment by hemal7735** [comment]
> git clone ...
> cd good-first-issue/data/
> vim projects.json and added an entry
> and npm run markdown

Hi @hpez 
Please do this after git clone.
1. cd good-first-issue
2. npm install

then you can add an entry in data/projects.json, and run npm run markdown.

**Comment by hpez** [comment]
Thanks that did the trick
