### ISSUE TITLE
Refactor @octokit/rest.js in search.js to use async/await

### ISSUE THREAD

**Issue by bnb** [bnb/good-first-issue#15]
Looks like we've published a version that is emitting a warning from `@octokit/rest.js` notifying that callbacks will be deprecated:

![image](https://user-images.githubusercontent.com/502396/48360416-2caa9280-e66d-11e8-9983-29c947577a9f.png)

Let's refactor using async/await.

**Comment by maddhruv** [comment]
ain't showing for me
![image](https://user-images.githubusercontent.com/18121502/48361386-66a88280-e6c7-11e8-9de0-df78c0223ae8.png)

**Comment by maddhruv** [comment]
please check the lock file
I am having the 15.x version

![image](https://user-images.githubusercontent.com/18121502/48361475-98214e00-e6c7-11e8-90a9-e1d91f7850ac.png)

**Comment by kennethvandenberghe** [comment]
Indeed, in 15.7.0 there are a few deprecations listed. Callbacks being among them. I will refactor things to use async await (and update the tests I made, since those expect the callback way for mocking).
