### ISSUE TITLE
Incomplete code comment.

### ISSUE THREAD

**Issue by sebastienvercammen** [bnb/good-first-issue#4]
Browsing around, I noticed this piece of incomplete comment text.

> Expects a ... passed

> do not need to ...

https://github.com/bnb/good-first-issue/blob/66d591a885c520aaf1797c32dac8e61d814afcf3/lib/search.js#L2

**Comment by bnb** [comment]
Thanks for letting me know! Should be fixed in https://github.com/bnb/good-first-issue/commit/10468d6872a92b41660ee82e59c651d450a3498b 🤗

**Comment by sebastienvercammen** [comment]
@bnb Super, thanks for the quick turn-around.

Small maintainer tip, should you ever need it: If you type something like "`Fixes #4`" in a PR and merge it, the Issue automatically gets closed. The reference itself will also be shown in the Issue. This helped save us a lot of time during our OS work.
