### ISSUE TITLE
Good first issue failing

### ISSUE THREAD

**Issue by gusma** [bnb/good-first-issue#45]
Hi! I'm getting this error while trying to run GFI:

![error-goodfirst](https://user-images.githubusercontent.com/140903/48850391-5491a880-ed87-11e8-8e95-5d5aad1bd0c9.jpg)

Why could this be happening?

**Comment by maddhruv** [comment]
please tell your
node version?

**Comment by maddhruv** [comment]
good-first-issue is supported for node > 8

**Comment by gusma** [comment]
Rats! 6.14. Sorry.

**Comment by maddhruv** [comment]
No Problem
Please update your node to the latest version
:smile:
