### ISSUE TITLE
Cannot find module '../data/projects.json'

### ISSUE THREAD

**Issue by bnb** [bnb/good-first-issue#46]
Source: https://twitter.com/jeremenichelli/status/1065261579271315456?s=20

**Comment by bnb** [comment]
Also got this on a different run: 
![image](https://user-images.githubusercontent.com/502396/48851202-75063680-ed78-11e8-9134-9428e596b263.png)

**Comment by maddhruv** [comment]
just checking :hourglass:

**Comment by bnb** [comment]
FWIW this is the LOC that's causing the issue: https://github.com/bnb/good-first-issue/blob/master/bin/prompt.js#L3

Can't reproduce locally but can easily reproduce from npm with npx and global install.

**Comment by jeremenichelli** [comment]
Still seeing this:

<img width="583" alt="screen shot 2018-11-21 at 17 12 59" src="https://user-images.githubusercontent.com/3856481/48853867-badef100-edb0-11e8-92be-07a0cfba92d3.png">

One issue could be that the build or publish script is ignoring the data folder, if not, I would suggest bundling the script before publish to avoid this. Sorry I don't have the time to inspect and put a fix in place :/
