### ISSUE TITLE
[README.md] - Automatic Generation of Projects in README.md/PROJECT_SUPPORTED.md

### ISSUE THREAD

**Issue by hemal7735** [bnb/good-first-issue#52]
As of now, in order to add projects we do 2 things:
1. add project in `data/projects.json`
2. update `README.md`

Step-2 might get forgotten sometime. This can be automated stuff as part of `npm script`.

We can have `PROJECT_SUPPORTED.md` where we list all the projects.

@bnb @maddhruv Do let me know your thoughts.

**Comment by bnb** [comment]
@hemal7735 Sounds good to me 👍
