### ISSUE TITLE
Add CI check for npm run markdown

### ISSUE THREAD

**Issue by bnb** [bnb/good-first-issue#63]
With https://github.com/bnb/good-first-issue/pull/60 being merged, we've got a new developer command: `npm run markdown`.

It would probably be wise to have a CI check to ensure this was run to lower maintenance burden on everyone ❤️

**Comment by hemal7735** [comment]
probably a test-case to validate the following?
1:1 correspondence between entries(README) and entries(data/projects.json)

**Comment by bnb** [comment]
Yup, that sounds like a good idea.

**Comment by hemal7735** [comment]
@bnb We can close this issue now.
