### ISSUE TITLE
MISC - Improve the process for adding new project

### ISSUE THREAD

**Issue by hemal7735** [bnb/good-first-issue#83]
#### What is the problem you are trying to solve?
Let's sit back for a moment and look back at how new project support is added.
1. Add project in `data.json`
2. run `npm run markdown` (Creates an Serial Number)
3. commit `data.json` and `README.md`

Now, what happens when you have multiple PRs? The serial number in README.md will cause conflicts and `rebase` must be performed to avoid conflicts. This creates a friction while adding new projects.

#### What can we do about it?
1. Remove the need of serial-numbers
2. Setup a system so that `README.md` gets updated automatically whenever `projects.json` is updated (May be some bot).

**Comment by hemal7735** [comment]
@bnb would you like to take an attention to this?

**Comment by bnb** [comment]
@hemal7735 yes that would be ideal. The best course of action (lowest effort) is likely to just remove the serial numbers 👍

**Comment by hemal7735** [comment]
This seem like not working 😞. I tried to replicate: https://github.com/hemal7735/good-first-issue/pull/2

**Comment by bnb** [comment]
We'd need to update both https://github.com/bnb/good-first-issue/blob/master/markdown.config.js and https://github.com/bnb/good-first-issue/blob/master/markdown.config.spec.js since we're testing Markdown compliance on that table.

**Comment by hemal7735** [comment]
I did that and then while testing I found out that GitHub still shows the conflicts, which fails the whole purpose. My bad!

**Comment by hemal7735** [comment]
Closing the issue as this does not seem achievable
